Junit setup/test
Cryxnoob/TeamProjectTH-BingenEP-1 pull request #39
Opened 2017-08-08 16:33 UTC by Zerocreative0815

added the junit setup in the pom and a test for helloworld  #4

2017-08-08 16:55 UTC, Zerocreative0815 commented
@nicolaiparlog

2017-08-09 07:29 UTC, nipafx requested changes
Almost there... :smiley:

2017-08-09 07:29 UTC, nicolaiparlog commented on pom.xml
> +                    <execution>
The four lines here duplicate what you already have aboce them and leads to a failing build. You have to remove them.

:bulb: Always run the build locally to make sure everything works as expected.

2017-08-09 07:29 UTC, nicolaiparlog commented on src/test/kotlin/HelloWorldtests/HelloWorldtest.kt
> +class HelloWorldtest{
The class (and the file) has to be called `HelloWorldTest` (note the upper case `T`) for Maven to pick it up. It worked when you see _Hello from the otherside!!_ on the command line.

2017-08-09 15:40 UTC, Zerocreative0815 commented
Closes #4

2017-08-09 15:41 UTC, merged

2017-08-10 08:22 UTC, nicolaiparlog commented
:bulb: "Closes ..."-Hinweise müssen in den ersten Kommentar des PUR, sonst funktionieren sie nicht.